#ifndef __TERRAIN__
#define __TERRAIN__

#include "Parser/Tile.hpp"
#include <unordered_map>
#include <vector>

enum E_TerrainType {
	TERRAIN_GRASS_NORMAL,
	TERRAIN_SOIL_NORMAL,
	TERRAIN_ROCK_NORMAL
};

enum E_TerrainTile {
	// floors
	// grass normal
	TERRAIN_GRASS_NORMAL_TOPLEFT, TERRAIN_GRASS_NORMAL_TOP,
	TERRAIN_GRASS_NORMAL_TOPRIGHT, TERRAIN_GRASS_NORMAL_LEFT,
	TERRAIN_GRASS_NORMAL_CENTER, TERRAIN_GRASS_NORMAL_RIGHT,
	TERRAIN_GRASS_NORMAL_BOTTOMLEFT, TERRAIN_GRASS_NORMAL_BOTTOM,
	TERRAIN_GRASS_NORMAL_BOTTOMRIGHT,
	TERRAIN_GRASS_NORMAL_VERT_TOP, TERRAIN_GRASS_NORMAL_VERT, TERRAIN_GRASS_NORMAL_VERT_BOTTOM,
	TERRAIN_GRASS_NORMAL_SINGLE,
	TERRAIN_GRASS_NORMAL_HORIZ_LEFT, TERRAIN_GRASS_NORMAL_HORIZ, TERRAIN_GRASS_NORMAL_HORIZ_RIGHT,
	// soil normal
	TERRAIN_SOIL_NORMAL_TOPLEFT, TERRAIN_SOIL_NORMAL_TOP,
	TERRAIN_SOIL_NORMAL_TOPRIGHT, TERRAIN_SOIL_NORMAL_LEFT,
	TERRAIN_SOIL_NORMAL_CENTER, TERRAIN_SOIL_NORMAL_RIGHT,
	TERRAIN_SOIL_NORMAL_BOTTOMLEFT, TERRAIN_SOIL_NORMAL_BOTTOM,
	TERRAIN_SOIL_NORMAL_BOTTOMRIGHT,
	TERRAIN_SOIL_NORMAL_VERT_TOP, TERRAIN_SOIL_NORMAL_VERT, TERRAIN_SOIL_NORMAL_VERT_BOTTOM,
	TERRAIN_SOIL_NORMAL_SINGLE,
	TERRAIN_SOIL_NORMAL_HORIZ_LEFT, TERRAIN_SOIL_NORMAL_HORIZ, TERRAIN_SOIL_NORMAL_HORIZ_RIGHT,
	// rock normal
	TERRAIN_ROCK_NORMAL_TOPLEFT, TERRAIN_ROCK_NORMAL_TOP,
	TERRAIN_ROCK_NORMAL_TOPRIGHT, TERRAIN_ROCK_NORMAL_LEFT,
	TERRAIN_ROCK_NORMAL_CENTER, TERRAIN_ROCK_NORMAL_RIGHT,
	TERRAIN_ROCK_NORMAL_BOTTOMLEFT, TERRAIN_ROCK_NORMAL_BOTTOM,
	TERRAIN_ROCK_NORMAL_BOTTOMRIGHT,
	TERRAIN_ROCK_NORMAL_VERT_TOP, TERRAIN_ROCK_NORMAL_VERT, TERRAIN_ROCK_NORMAL_VERT_BOTTOM,
	TERRAIN_ROCK_NORMAL_SINGLE,
	TERRAIN_ROCK_NORMAL_HORIZ_LEFT, TERRAIN_ROCK_NORMAL_HORIZ, TERRAIN_ROCK_NORMAL_HORIZ_RIGHT
};

std::unordered_map<E_TerrainType, std::vector<E_TerrainTile>> createTileMasksMap();

class Terrain {
	private:
	unsigned int m_iFlags = 0;
	static std::unordered_map<E_TerrainType, std::vector<E_TerrainTile>> s_mTerrainMasks;

	public:
	static const int TERRAIN_FLAG_WALKABLE = 0x1;
	static const int TERRAIN_FLAG_OBSTRUCTING_VIEW = 0x2;

	static E_TerrainTile getTerrainTile(E_TerrainType type, int index);
	void setFlags(unsigned int flags);
	bool hasFlag(unsigned int flag);
};

#endif
